apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todoapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/maniak-academy/argco-eks-maniak
    targetRevision: HEAD
    path: todoapp
  destination: 
    server: https://kubernetes.default.svc
    namespace: todoapp

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
