apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-todoapp
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-admin-role
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: my-admin-binding
subjects:
- kind: ServiceAccount
  name: admin-todoapp
  namespace: default
roleRef:
  kind: ClusterRole
  name: my-admin-role
  apiGroup: rbac.authorization.k8s.io
