apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp
spec:
  selector:
    matchLabels:
      app: todoapp
  replicas: 2
  template:
    metadata:
      labels:
        app: todoapp
    spec:
      containers:
      - name: todoapp
        image: 616973157416.dkr.ecr.us-east-1.amazonaws.com/sebbycorp-simple-app-demo:v0.0.5
        ports:
        - containerPort: 5000
